# Sidebar navigation

# EN
- label: 'Home'
  link: '/en'
- label: 'Overview'
  link: '/en/overview'
- label: 'Installation & Run'
  link: '/en/installation'
- label: Dev Components
  link: '/en'
  items:
    - label: 'IO Component'
      link: '/en/components/io'
    - label: 'Output Component'
      link: '/en/components/output'
    - label: 'Custom Component'
      link: '/en/components/custom'
    - label: 'Node Properties'
      link: '/en/components/nodeproperties'
- label: Useful Links
  link: '/en'
  items:
    - label: Online OpenCV-Flow IDE
      link: https://online.opencvflow.org/
    - label: Git OpenCV-Flow
      link: https://github.com/Piemontez/opencvflow
    - label: Git OpenCV-Flow Docs
      link: https://github.com/Piemontez/opencvflowdocs

# PT
- label: 'Início'
  link: '/pt'
- label: 'Visão geral'
  link: '/pt/overview'
- label: 'Instalação e Execução'
  link: '/pt/installation'
- label: Dev Componentes
  link: '/pt'
  items:
    - label: 'IO Component'
      link: '/pt/components/io'
    - label: 'Output Component'
      link: '/pt/components/output'
    - label: 'Custom Component'
      link: '/pt/components/custom'
    - label: 'Node Properties'
      link: '/pt/components/nodeproperties'
- label: Links Úteis
  link: '/pt'
  items:
    - label: Online OpenCV-Flow IDE
      link: https://online.opencvflow.org/
    - label: Git OpenCV-Flow
      link: https://github.com/Piemontez/opencvflow
    - label: Git OpenCV-Flow Docs
      link: https://github.com/Piemontez/opencvflowdocs
